_BASE_: "Base-YOLOF.yaml"
DATASETS:
  TRAIN: ("erosive_train",)
  TEST: ("erosive_test",)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  RETINANET:
    NUM_CLASSES: 1
  ROI_HEADS:
    NUM_CLASSES: 1
  SEM_SEG_HEAD:
    NUM_CLASSES: 1
  YOLOF:
    DECODER:
      NUM_CLASSES: 1
SOLVER:
  BASE_LR: 0.06
  IMS_PER_BATCH: 32
  WARMUP_ITERS: 3000
OUTPUT_DIR: "/data1/qilei_chen/DATA/erosive/work_dirs_yolof/R_50_C5_1x"
